name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
       steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and run Laradock containers
      run: |
        cd ../laradock
        docker compose up -d nginx mysql redis workspace

    - name: Install Laravel dependencies
      run: |
        cd ../laradock/workspace 
        composer install

    - name: Generate application key
      run: |
        cd ../laradock/workspace
        php artisan key:generate

    - name: Run database migrations
      run: |
        cd ../laradock/workspace
        php artisan migrate --force

    - name: Run tests
      run: |
        cd ../laradock/workspace
        php artisan test

    - name: Stop Laradock containers
      run: |
        cd ../laradock
        docker-compose stop
        