name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: self-hosted

    steps:
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Build and run Laradock containers
      run: |
        pwd
        cd laradock
        docker compose up -d nginx mysql redis workspace

    - name: Install Laravel dependencies
      run: |
        cd laradock
        docker-compose exec workspace bash
        composer install

    - name: Generate application key
      run: |
        cd laradock
        docker-compose exec workspace bash
        php artisan key:generate

    - name: Run database migrations
      run: |
        cd laradock
        docker-compose exec workspace bash
        php artisan migrate --force

    - name: Run passport install
      run: |
        cd laradock
        docker-compose exec workspace bash
        php artisan passport:install --uuids

    - name: Run seed
      run: |
        cd laradock
        docker-compose exec workspace bash
        php artisan db:seed

    - name: Run tests
      run: |
        cd laradock/workspace
        php artisan test --coverage

    - name: Stop Laradock containers
      run: |
        cd laradock
        docker compose stop
        
