name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: windows-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Build and run Laradock containers
      run: |
        cd laradock
        docker compose up -d nginx mysql redis workspace

    - name: Install Laravel dependencies
      run: |
        cd laradock/workspace 
        composer install

    - name: Generate application key
      run: |
        cd laradock/workspace
        php artisan key:generate

    - name: Run database migrations
      run: |
        cd laradock/workspace
        php artisan migrate --force

    - name: Run tests
      run: |
        cd laradock/workspace
        php artisan test

    - name: Stop Laradock containers
      run: |
        cd laradock
        docker-compose stop
        
